# Generated by Django 3.2.4 on 2021-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
