# Generated by Django 3.2.4 on 2021-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_faqitem_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image')], default='TEXT', max_length=5),
        ),
    ]
