# Generated by Django 3.2.4 on 2021-12-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('TEXT', 'Text')], default='TEXT', max_length=5),
        ),
    ]
