# Generated by Django 3.2.4 on 2021-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_setting_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]

##please work